/* Generated by scripts/cut-rig.py. Sizes are source pixels, the rig's layout unit. */
export const PART_SIZE = {
  "eyes-open": {
    "w": 688,
    "h": 453,
    "ink": {
      "x": 157,
      "y": 186,
      "w": 373,
      "h": 87
    }
  },
  "eyes-blink": {
    "w": 688,
    "h": 452,
    "ink": {
      "x": 65,
      "y": 201,
      "w": 571,
      "h": 70
    }
  },
  "eyes-happy": {
    "w": 688,
    "h": 453,
    "ink": {
      "x": 76,
      "y": 187,
      "w": 536,
      "h": 81
    }
  },
  "eyes-worried": {
    "w": 688,
    "h": 452,
    "ink": {
      "x": 104,
      "y": 112,
      "w": 477,
      "h": 182
    }
  },
  "eyes-determined": {
    "w": 688,
    "h": 452,
    "ink": {
      "x": 103,
      "y": 106,
      "w": 482,
      "h": 183
    }
  },
  "eyes-sleepy": {
    "w": 688,
    "h": 452,
    "ink": {
      "x": 79,
      "y": 186,
      "w": 535,
      "h": 105
    }
  },
  "mouth-smile": {
    "w": 275,
    "h": 295,
    "ink": {
      "x": 51,
      "y": 110,
      "w": 175,
      "h": 77
    }
  },
  "mouth-laugh": {
    "w": 413,
    "h": 295,
    "ink": {
      "x": 47,
      "y": 28,
      "w": 318,
      "h": 244
    }
  },
  "mouth-frown": {
    "w": 295,
    "h": 295,
    "ink": {
      "x": 44,
      "y": 105,
      "w": 212,
      "h": 85
    }
  },
  "mouth-yawn": {
    "w": 236,
    "h": 295,
    "ink": {
      "x": 53,
      "y": 69,
      "w": 130,
      "h": 157
    }
  },
  "mouth-half": {
    "w": 393,
    "h": 295,
    "ink": {
      "x": 64,
      "y": 94,
      "w": 277,
      "h": 111
    }
  },
  "mouth-o": {
    "w": 177,
    "h": 295,
    "ink": {
      "x": 41,
      "y": 95,
      "w": 94,
      "h": 105
    }
  },
  "body": {
    "w": 904,
    "h": 1350,
    "ink": {
      "x": 1,
      "y": 1,
      "w": 898,
      "h": 1344
    }
  },
  "prop-scale": {
    "w": 638,
    "h": 582,
    "ink": {
      "x": 0,
      "y": 0,
      "w": 636,
      "h": 579
    }
  },
  "prop-phone": {
    "w": 350,
    "h": 596,
    "ink": {
      "x": 0,
      "y": 0,
      "w": 348,
      "h": 593
    }
  },
  "prop-dumbbell": {
    "w": 742,
    "h": 343,
    "ink": {
      "x": 1,
      "y": 1,
      "w": 739,
      "h": 340
    }
  },
  "prop-plane": {
    "w": 736,
    "h": 514,
    "ink": {
      "x": 1,
      "y": 0,
      "w": 732,
      "h": 512
    }
  },
  "prop-clock": {
    "w": 492,
    "h": 555,
    "ink": {
      "x": 0,
      "y": 1,
      "w": 489,
      "h": 551
    }
  },
  "prop-sparks": {
    "w": 610,
    "h": 565,
    "ink": {
      "x": 0,
      "y": 1,
      "w": 608,
      "h": 561
    }
  },
  "arm-down": {
    "w": 295,
    "h": 707,
    "ink": {
      "x": 47,
      "y": 29,
      "w": 196,
      "h": 662
    },
    "pivot": {
      "x": 177,
      "y": 63
    }
  },
  "arm-wave": {
    "w": 412,
    "h": 688,
    "ink": {
      "x": 47,
      "y": 30,
      "w": 310,
      "h": 637
    },
    "pivot": {
      "x": 88,
      "y": 629
    }
  },
  "arm-hip": {
    "w": 393,
    "h": 530,
    "ink": {
      "x": 40,
      "y": 29,
      "w": 319,
      "h": 483
    },
    "pivot": {
      "x": 261,
      "y": 55
    }
  },
  "arm-up": {
    "w": 570,
    "h": 550,
    "ink": {
      "x": 47,
      "y": 22,
      "w": 486,
      "h": 509
    },
    "pivot": {
      "x": 85,
      "y": 482
    }
  },
  "leg-left": {
    "w": 260,
    "h": 448,
    "ink": {
      "x": 10,
      "y": 0,
      "w": 225,
      "h": 440
    },
    "pivot": {
      "x": 157,
      "y": 4
    }
  },
  "leg-right": {
    "w": 259,
    "h": 448,
    "ink": {
      "x": 21,
      "y": 0,
      "w": 224,
      "h": 440
    },
    "pivot": {
      "x": 102,
      "y": 4
    }
  }
} as const;

export const PART_SRC = {
  'arm-down': require('../../assets/illustrations/rig/arm-down.png'),
  'arm-hip': require('../../assets/illustrations/rig/arm-hip.png'),
  'arm-up': require('../../assets/illustrations/rig/arm-up.png'),
  'arm-wave': require('../../assets/illustrations/rig/arm-wave.png'),
  'body': require('../../assets/illustrations/rig/body.png'),
  'eyes-blink': require('../../assets/illustrations/rig/eyes-blink.png'),
  'eyes-determined': require('../../assets/illustrations/rig/eyes-determined.png'),
  'eyes-happy': require('../../assets/illustrations/rig/eyes-happy.png'),
  'eyes-open': require('../../assets/illustrations/rig/eyes-open.png'),
  'eyes-sleepy': require('../../assets/illustrations/rig/eyes-sleepy.png'),
  'eyes-worried': require('../../assets/illustrations/rig/eyes-worried.png'),
  'leg-left': require('../../assets/illustrations/rig/leg-left.png'),
  'leg-right': require('../../assets/illustrations/rig/leg-right.png'),
  'mouth-frown': require('../../assets/illustrations/rig/mouth-frown.png'),
  'mouth-half': require('../../assets/illustrations/rig/mouth-half.png'),
  'mouth-laugh': require('../../assets/illustrations/rig/mouth-laugh.png'),
  'mouth-o': require('../../assets/illustrations/rig/mouth-o.png'),
  'mouth-smile': require('../../assets/illustrations/rig/mouth-smile.png'),
  'mouth-yawn': require('../../assets/illustrations/rig/mouth-yawn.png'),
  'prop-clock': require('../../assets/illustrations/rig/prop-clock.png'),
  'prop-dumbbell': require('../../assets/illustrations/rig/prop-dumbbell.png'),
  'prop-phone': require('../../assets/illustrations/rig/prop-phone.png'),
  'prop-plane': require('../../assets/illustrations/rig/prop-plane.png'),
  'prop-scale': require('../../assets/illustrations/rig/prop-scale.png'),
  'prop-sparks': require('../../assets/illustrations/rig/prop-sparks.png'),
} as const;

export type PartName = keyof typeof PART_SRC;
