/* Generated by scripts/cut-rig.py. Sizes are source pixels, the rig's layout unit. */
export const PART_SIZE = {
  "eyes-open": {
    "w": 688,
    "h": 453
  },
  "eyes-blink": {
    "w": 688,
    "h": 452
  },
  "eyes-happy": {
    "w": 688,
    "h": 453
  },
  "eyes-worried": {
    "w": 688,
    "h": 452
  },
  "eyes-determined": {
    "w": 688,
    "h": 452
  },
  "eyes-sleepy": {
    "w": 688,
    "h": 452
  },
  "mouth-smile": {
    "w": 275,
    "h": 295
  },
  "mouth-laugh": {
    "w": 413,
    "h": 295
  },
  "mouth-frown": {
    "w": 295,
    "h": 295
  },
  "mouth-yawn": {
    "w": 236,
    "h": 295
  },
  "mouth-half": {
    "w": 393,
    "h": 295
  },
  "mouth-o": {
    "w": 177,
    "h": 295
  },
  "body": {
    "w": 904,
    "h": 1350
  },
  "prop-scale": {
    "w": 638,
    "h": 582
  },
  "prop-phone": {
    "w": 350,
    "h": 596
  },
  "prop-dumbbell": {
    "w": 742,
    "h": 343
  },
  "prop-plane": {
    "w": 736,
    "h": 514
  },
  "prop-clock": {
    "w": 492,
    "h": 555
  },
  "prop-sparks": {
    "w": 610,
    "h": 565
  },
  "arm-down": {
    "w": 295,
    "h": 707,
    "pivot": {
      "x": 177,
      "y": 63
    }
  },
  "arm-wave": {
    "w": 412,
    "h": 688,
    "pivot": {
      "x": 88,
      "y": 629
    }
  },
  "arm-hip": {
    "w": 393,
    "h": 530,
    "pivot": {
      "x": 261,
      "y": 55
    }
  },
  "arm-up": {
    "w": 570,
    "h": 550,
    "pivot": {
      "x": 85,
      "y": 482
    }
  }
} as const;

export const PART_SRC = {
  'arm-down': require('../../assets/illustrations/rig/arm-down.png'),
  'arm-hip': require('../../assets/illustrations/rig/arm-hip.png'),
  'arm-up': require('../../assets/illustrations/rig/arm-up.png'),
  'arm-wave': require('../../assets/illustrations/rig/arm-wave.png'),
  'body': require('../../assets/illustrations/rig/body.png'),
  'eyes-blink': require('../../assets/illustrations/rig/eyes-blink.png'),
  'eyes-determined': require('../../assets/illustrations/rig/eyes-determined.png'),
  'eyes-happy': require('../../assets/illustrations/rig/eyes-happy.png'),
  'eyes-open': require('../../assets/illustrations/rig/eyes-open.png'),
  'eyes-sleepy': require('../../assets/illustrations/rig/eyes-sleepy.png'),
  'eyes-worried': require('../../assets/illustrations/rig/eyes-worried.png'),
  'mouth-frown': require('../../assets/illustrations/rig/mouth-frown.png'),
  'mouth-half': require('../../assets/illustrations/rig/mouth-half.png'),
  'mouth-laugh': require('../../assets/illustrations/rig/mouth-laugh.png'),
  'mouth-o': require('../../assets/illustrations/rig/mouth-o.png'),
  'mouth-smile': require('../../assets/illustrations/rig/mouth-smile.png'),
  'mouth-yawn': require('../../assets/illustrations/rig/mouth-yawn.png'),
  'prop-clock': require('../../assets/illustrations/rig/prop-clock.png'),
  'prop-dumbbell': require('../../assets/illustrations/rig/prop-dumbbell.png'),
  'prop-phone': require('../../assets/illustrations/rig/prop-phone.png'),
  'prop-plane': require('../../assets/illustrations/rig/prop-plane.png'),
  'prop-scale': require('../../assets/illustrations/rig/prop-scale.png'),
  'prop-sparks': require('../../assets/illustrations/rig/prop-sparks.png'),
} as const;

export type PartName = keyof typeof PART_SRC;
