/* Generated by scripts/cut-rig.py. Sizes are source pixels, the rig's layout unit. */
export const PART_SIZE = {
  "eyes-open": {
    "w": 688,
    "h": 453
  },
  "eyes-blink": {
    "w": 688,
    "h": 452
  },
  "eyes-happy": {
    "w": 688,
    "h": 453
  },
  "eyes-worried": {
    "w": 688,
    "h": 452
  },
  "eyes-determined": {
    "w": 688,
    "h": 452
  },
  "eyes-sleepy": {
    "w": 688,
    "h": 452
  },
  "mouth-smile": {
    "w": 275,
    "h": 295
  },
  "mouth-laugh": {
    "w": 413,
    "h": 295
  },
  "mouth-frown": {
    "w": 295,
    "h": 295
  },
  "mouth-yawn": {
    "w": 236,
    "h": 295
  },
  "mouth-half": {
    "w": 393,
    "h": 295
  },
  "mouth-o": {
    "w": 177,
    "h": 295
  },
  "body": {
    "w": 904,
    "h": 1350
  }
} as const;

export const PART_SRC = {
  'body': require('../../assets/illustrations/rig/body.png'),
  'eyes-blink': require('../../assets/illustrations/rig/eyes-blink.png'),
  'eyes-determined': require('../../assets/illustrations/rig/eyes-determined.png'),
  'eyes-happy': require('../../assets/illustrations/rig/eyes-happy.png'),
  'eyes-open': require('../../assets/illustrations/rig/eyes-open.png'),
  'eyes-sleepy': require('../../assets/illustrations/rig/eyes-sleepy.png'),
  'eyes-worried': require('../../assets/illustrations/rig/eyes-worried.png'),
  'mouth-frown': require('../../assets/illustrations/rig/mouth-frown.png'),
  'mouth-half': require('../../assets/illustrations/rig/mouth-half.png'),
  'mouth-laugh': require('../../assets/illustrations/rig/mouth-laugh.png'),
  'mouth-o': require('../../assets/illustrations/rig/mouth-o.png'),
  'mouth-smile': require('../../assets/illustrations/rig/mouth-smile.png'),
  'mouth-yawn': require('../../assets/illustrations/rig/mouth-yawn.png'),
} as const;

export type PartName = keyof typeof PART_SRC;
