"""Cut Ember's rig parts out of the generated part sheets.

Each part is cut from a fixed box centred on a chosen point (the middle of the eye line, the
shoulder end of an arm), not trimmed to its own edges. That keeps the anchor where the rig expects
it: open eyes and closed eyes share a centre, so a blink swaps in place instead of jumping.

    python3 scripts/cut-rig.py

Writes assets/illustrations/rig/<part>@2x.png, @3x.png and rig/parts.json (each part's size in
source pixels, which is the unit src/components/EmberRig.tsx lays the rig out in).
"""
import json
import os
import subprocess
import sys

from PIL import Image, ImageFilter

ROOT = os.path.join(os.path.dirname(__file__), '..', 'assets', 'illustrations')
OUT = os.path.join(ROOT, 'rig')

# sheet -> {part: (centre x, centre y, half width, half height)} in the sheet's own pixels.
# Preview coordinates were read at 1400 px wide; SCALE converts them to the 2752 px source.
SCALE = 2752 / 1400
SHEETS = {
    # The body is trimmed to its own edges; everything else is placed relative to it.
    'ember-body.jpeg': {'body': 'trim'},
    'ember-faces.jpeg': {
        'eyes-open': (278, 162, 175, 115),
        'eyes-blink': (705, 165, 175, 115),
        'eyes-happy': (1135, 160, 175, 115),
        'eyes-worried': (280, 345, 175, 115),
        'eyes-determined': (712, 345, 175, 115),
        'eyes-sleepy': (1135, 355, 175, 115),
        'mouth-smile': (182, 568, 70, 75),
        'mouth-laugh': (400, 568, 105, 75),
        'mouth-frown': (622, 568, 75, 75),
        'mouth-yawn': (818, 568, 60, 75),
        'mouth-half': (1025, 558, 100, 75),
        'mouth-o': (1218, 568, 45, 75),
    },
}
SHEETS.update(json.load(open(os.path.join(OUT, 'sheets.json'))) if os.path.exists(os.path.join(OUT, 'sheets.json')) else {})


def key(img):
    """Magenta to transparent, with edges unmixed and the matte pulled in slightly."""
    img = img.convert('RGB')
    w, h = img.size
    px = img.load()
    out = Image.new('RGBA', (w, h))
    op = out.load()
    FULL, NONE = 110, 190
    for y in range(h):
        for x in range(w):
            r, g, b = px[x, y]
            dist = 255 - (min(r, b) - g)
            if dist <= FULL:
                op[x, y] = (0, 0, 0, 0)
            elif dist >= NONE:
                op[x, y] = (r, g, b, 255)
            else:
                a = (dist - FULL) / (NONE - FULL)
                un = lambda o, m: max(0, min(255, int((o - (1 - a) * m) / a)))
                op[x, y] = (un(r, 255), un(g, 0), un(b, 255), int(a * 255))
    r, g, b, al = out.split()
    return Image.merge('RGBA', (r, g, b, al.filter(ImageFilter.MinFilter(3))))


parts = json.load(open(os.path.join(OUT, 'parts.json'))) if os.path.exists(os.path.join(OUT, 'parts.json')) else {}
os.makedirs(OUT, exist_ok=True)
for sheet, boxes in SHEETS.items():
    src = os.path.join(ROOT, 'source', sheet)
    if not os.path.exists(src):
        print('missing', sheet, file=sys.stderr)
        continue
    keyed = key(Image.open(src))
    for name, spec in boxes.items():
        if spec == 'trim':
            part = keyed.crop(keyed.getbbox())
        else:
            cx, cy, hw, hh = spec
            box = tuple(round(v * SCALE) for v in (cx - hw, cy - hh, cx + hw, cy + hh))
            part = keyed.crop(box)
        parts[name] = {'w': part.width, 'h': part.height}
        # Parts are laid out in source pixels; @3x is the source size, @2x two thirds of it.
        part.save(os.path.join(OUT, f'{name}@3x.png'), optimize=True)
        part.resize((round(part.width * 2 / 3), round(part.height * 2 / 3)), Image.LANCZOS).save(
            os.path.join(OUT, f'{name}@2x.png'), optimize=True
        )
        print(name, part.size)
json.dump(parts, open(os.path.join(OUT, 'parts.json'), 'w'), indent=1)

# The app's manifest: every part's size and its require(), so the rig can't reference a part
# that wasn't cut.
ts = ['/* Generated by scripts/cut-rig.py. Sizes are source pixels, the rig\'s layout unit. */']
ts.append('export const PART_SIZE = ' + json.dumps(parts, indent=2) + ' as const;')
ts.append('')
ts.append('export const PART_SRC = {')
for n in sorted(parts):
    ts.append(f"  '{n}': require('../../assets/illustrations/rig/{n}.png'),")
ts.append('} as const;')
ts.append('')
ts.append('export type PartName = keyof typeof PART_SRC;')
open(os.path.join(os.path.dirname(__file__), '..', 'src', 'components', 'emberParts.ts'), 'w').write('\n'.join(ts) + '\n')
